title: Aoife McCloskey <br> PhD <br>
logo: "/images/professional_photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>Research Data Scientist, Educator & Python Programmer |<br>
  Seeking opportunities in Data Science, Green Tech & Education <br>
  <a href="/pdf/cv_industry_oct22.pdf">My CV</a><br> || <a href = "mailto: aoifemccloskey91@gmail.com">Email</a><br>
  <a href="https://www.linkedin.com/in/mccloska/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
